name: deploy code build
on: push
env:
  imageName: "myjavaapp"
jobs:
 CICDjobs:
  runs-on: ubuntu-latest
  steps:
  - name: clone current repository
    uses: actions/checkout@v2
  - name: setup java17 and maven
    uses: actions/setup-java@v2
    with:
      distribution: 'temurin'
      java-version: '17'
      cache: 'maven'
  - name: build the code
    run: mvn clean package
